import Dropdown from './components/ui/Dropdown';
import logoSvg from './logo.svg?raw';
import {useEffect,useMemo,useRef,useState} from 'react';
import {open,save} from '@tauri-apps/plugin-dialog';
import {getCurrentWebview} from '@tauri-apps/api/webview';
import CommandPalette from './CommandPalette';
import Onboarding from './Onboarding';
import {isMedia,isSubtitle,withSubtitles} from './attachments';
import {Terminal,SlidersHorizontal,Layers3,ListVideo,Download,Globe2,FolderOpen,ArrowUpRight,Play,Copy,Check,Plus,Search,Film,AudioLines,Sparkles,RotateCcw,X,Trash2,ChevronRight,HardDrive,FileJson,Sun,Moon,Settings2,ArrowDownToLine,ShieldCheck} from 'lucide-react';
import FormatSection from './components/sections/FormatSection';
import VideoSection from './components/sections/VideoSection';
import AudioSection from './components/sections/AudioSection';
import FiltersSection from './components/sections/FiltersSection';
import OptionsSection from './components/sections/OptionsSection';
import {useFfmpegForm} from './hooks/useFfmpegForm';
import {buildPlans,displayPlans} from './lib/ffmpeg';
import util from './lib/util';
import presets from './lib/presets';
import defaults from './lib/defaults';
import {deepMerge} from './lib/merge';
import {reconcile} from './lib/reconcile';
import type {IFFMpegOptionsForm} from './lib/types';
import {desktop,native,empty,type Snapshot,type Saved,type Release} from './native';
import {t,languages,loadLanguage,setLanguage,coverage,importLanguagePack,exportLanguageTemplate} from './i18n';

const filename=(s:string)=>s.split(/[\\/]/).pop()||s;
const groups=presets.getPresetOptions().filter(g=>!['custom','saved'].includes(g.id));
const recipes=groups.flatMap(g=>g.data.map(p=>({...p,group:g.name})));
function downloadJson(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function readLocal<T,>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
export default function App(){
 const editor=useFfmpegForm();const {form,setForm,update,updateFormat,updateVideo}=editor;
 const [page,setPage]=useState('Builder'),[tab,setTab]=useState('Video'),[locale,setLocale]=useState(loadLanguage),[light,setLight]=useState(()=>readLocal("encodeck-light",false));
 const [snap,setSnap]=useState<Snapshot>(empty),[saved,setSaved]=useState<Saved[]>(()=>readLocal('commander-presets',[]));
 const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('All');
 const [media,setMedia]=useState<any>(null),[releases,setReleases]=useState<Release[]>([]),[jobId,setJobId]=useState('');
 const [onboarding,setOnboarding]=useState(()=>!readLocal("encodeck-onboarded",false));
 const [subtitles,setSubtitles]=useState<string[]>([]),[batch,setBatch]=useState<string[]>([]),[dragging,setDragging]=useState(false),[appRelease,setAppRelease]=useState<any>(null);
 const dropHandler=useRef<(paths:string[])=>void>(()=>{});
 dropHandler.current=(paths)=>{const subs=paths.filter(isSubtitle),files=paths.filter(isMedia);setSubtitles(p=>[...new Set([...p,...subs])]);if(files.length){update('io',{input:files[0],output:files[0].replace(/\.[^./\\]+$/,'')+'-encoded.'+(form.format.container||'mp4')});setBatch(files.slice(1))}if(!subs.length&&!files.length)setError(t('No supported media files found'));else setMessage(t('Files added'));setDragging(false);setPage('Builder')};
 useEffect(()=>{if(!desktop)return;let disposed=false;let stop:(()=>void)|undefined;getCurrentWebview().onDragDropEvent(e=>{if(e.payload.type==='drop')dropHandler.current(e.payload.paths);else setDragging(e.payload.type==='enter'||e.payload.type==='over')}).then(unlisten=>{if(disposed)unlisten();else stop=unlisten}).catch(e=>setError(String(e)));return()=>{disposed=true;stop?.()}},[]);
 const [name,setName]=useState(''),[editId,setEditId]=useState(''),[json,setJson]=useState(false),[custom,setCustom]=useState(false),[customArgs,setCustomArgs]=useState('');
 const modal=useRef<HTMLDialogElement>(null),importRef=useRef<HTMLInputElement>(null),langRef=useRef<HTMLInputElement>(null);
 const initialized=useRef(false),probeToken=useRef(0);
 useEffect(()=>{if(!initialized.current){const draft=readLocal<IFFMpegOptionsForm|null>('commander-draft',null);if(draft?.io&&draft?.video)setForm(reconcile(deepMerge(defaults(),draft as never) as unknown as IFFMpegOptionsForm));initialized.current=true}},[]);
 useEffect(()=>{if(initialized.current)localStorage.setItem('commander-draft',JSON.stringify(form))},[form]);
 async function refresh(){if(desktop){const next=await native<Snapshot>('snapshot');setSnap(next);setSaved(next.config.presets)}}
 useEffect(()=>{let disposed=false;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{if(!disposed)await refresh()}catch(e){if(!disposed)setError(String(e))}if(!disposed)timer=setTimeout(poll,750)};void poll();return()=>{disposed=true;clearTimeout(timer)}},[]);
 useEffect(()=>{probeToken.current++;setMedia(null)},[form.io.input]);
 useEffect(()=>{document.documentElement.dataset.theme=light?'commander-light':'commander';localStorage.setItem('encodeck-light',JSON.stringify(light))},[light]);
 const active=snap.config.versions.find(v=>v.id===snap.config.active);
 const derived=useMemo(()=>{try{if(custom){const a=JSON.parse(customArgs);if(!Array.isArray(a)||!a.every(row=>Array.isArray(row)&&row.every(v=>typeof v==='string')))throw new Error('Expected an array of argument arrays');return {plans:a as string[][],error:''}}return{plans:buildPlans(util.transform(form) as never),error:''}}catch(e){return{plans:[] as string[][],error:String(e).replace(/^Error: /,'')}}},[form,custom,customArgs]);
 const combined=useMemo(()=>{try{return {plans:withSubtitles(derived.plans,subtitles,form.format.container||'mp4'),error:derived.error}}catch(e){return{plans:[],error:String(e)}}},[derived,subtitles,form.format.container]);
 const command=displayPlans(combined.plans), jobs=snap.jobs, running=jobs.filter(j=>['queued','running'].includes(j.status));
 const current=jobs.find(j=>j.id===jobId)||jobs.at(-1);
 const selectedRecipe=recipes.find(p=>p.value===selected)?.name||saved.find(p=>p.id===selected)?.name;
 async function action(key:string,fn:()=>Promise<unknown>){setBusy(key);setError('');try{await fn()}catch(e){setError(String(e).replace(/^Error: /,''))}finally{setBusy('')}}
 async function persist(next:Saved[]){if(desktop)await native('save_presets',{presets:next});else localStorage.setItem('commander-presets',JSON.stringify(next));setSaved(next)}
 function applyPreset(id:string){const data=recipes.some(p=>p.value===id)?presets.getPreset(id):saved.find(p=>p.id===id)?.data;if(!data)return;const next=deepMerge(defaults(),data as Record<string,unknown>);next.io={...form.io};setForm(reconcile(next as unknown as IFFMpegOptionsForm));setSelected(id);setCustom(false);setMessage(t('Preset applied'));setPage('Builder')}
 async function browse(which:'input'|'output'){await action('browse',async()=>{const path=which==='input'?await open({multiple:false,title:t('Source file')}):await save({defaultPath:form.io.output,title:t('Output file')});if(typeof path==='string'){update('io',{[which]:path,...(which==='input'?{output:path.replace(/\.[^./\\]+$/,'')+'-encoded.'+(form.format.container||'mp4')}:{})})}})}
 async function analyze(){await action('probe',async()=>{const token=++probeToken.current;const result=await native<any>('probe',{path:form.io.input});if(token===probeToken.current)setMedia(result)})}
 function autoPreset(){if(!media)return;const video=media.streams?.find((s:any)=>s.codec_type==='video');const next=defaults();next.io={...form.io};next.format.container=video?'mp4':'m4a';next.video.codec=video?'x264':'none';next.video.pass='crf';next.video.crf=23;next.video.preset='medium';next.video.pixel_format='yuv420p';next.video.faststart=!!video;next.video.size=video?.width>1920?'1920':'source';next.audio.codec='aac';next.audio.quality='192k';setForm(reconcile(next as unknown as IFFMpegOptionsForm));setSelected('');setCustom(false);setMessage(t('Automatic preset applied'));}
 async function enqueue(){await action('run',async()=>{const plans=structuredClone(combined.plans);if(!plans.length)throw new Error(combined.error);const output=plans.at(-1)!.at(-1)!;const id=await native<string>('enqueue',{plans,output,duration:form.format.clip?0:Number(media?.format?.duration)||0});setJobId(id);await refresh();setMessage(t('Added to queue'))})}
 async function enqueueBatch(){await action('batch',async()=>{let count=0;for(const path of batch){const next={...form,io:{input:path,output:path.replace(/\.[^./\\]+$/,'')+'-encoded.'+(form.format.container||'mp4')}};await native('enqueue',{plans:buildPlans(util.transform(next) as never),output:next.io.output,duration:0});count++;setBatch(p=>p.filter(f=>f!==path))}await refresh();setMessage(`${count} · ${t('Added to queue')}`)})}
 async function addFiles(){await action('files',async()=>{const paths=await open({multiple:true,title:t('Add media or subtitles')});if(paths)dropHandler.current(typeof paths==='string'?[paths]:paths)})}
 function saveDialog(id=''){setEditId(id);setName(saved.find(p=>p.id===id)?.name||'');modal.current?.showModal()}
 async function savePreset(){await action('save',async()=>{if(!name.trim())return;const id=editId||crypto.randomUUID();const data={...form,io:undefined};const next={id,name:name.trim(),data:data as unknown as Record<string,unknown>};await persist(editId?saved.map(p=>p.id===id?next:p):[...saved,next]);setSelected(id);modal.current?.close();setMessage(t('Preset saved'))})}
 const selectLocale=(value:string)=>{setLanguage(value);setLocale(value)};
 return <div className="app-shell" data-locale={locale}>
 <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Builder')}}><span role="img" aria-label="Encodeck" className="brand-logo" dangerouslySetInnerHTML={{__html:logoSvg}}/></a><div className="workspace-label">{t('WORKSPACE')}</div><nav>{[{id:'Builder',icon:SlidersHorizontal},{id:'Presets',icon:Layers3},{id:'Queue',icon:ListVideo},{id:'History',icon:RotateCcw},{id:'Settings',icon:Settings2}].map(({id,icon:Icon})=><button key={id} className={`nav-item ${(page===id||(id==='Settings'&&['Appearance','Versions','Updates','Languages'].includes(page)))?'active':''}`} onClick={()=>setPage(id==='Settings'?'Appearance':id)}><Icon size={18}/><span>{t(id)}</span>{id==='Queue'&&running.length>0&&<span className="badge badge-primary badge-sm">{running.length}</span>}{(page===id||(id==='Settings'&&['Appearance','Versions','Updates','Languages'].includes(page)))&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="engine-status"><span className={`status ${active?'status-success':'status-warning'}`}/><div><strong>{active?`FFmpeg ${active.name}`:t('Engine not configured')}</strong><small>{desktop?t('Local Rust engine'):t('Browser preview')}</small></div></div><div className="version-label">DESKTOP 1.0 <span>RUST + TAURI</span></div></div></aside>
 <div className="main-shell"><header className="topbar"><Dropdown className="select select-sm mobile-nav" aria-label={t("Navigation")} value={page} onChange={e=>setPage(e.target.value)}>{["Builder","Presets","Queue","History","Appearance"].map(p=><option key={p} value={p}>{t(p)}</option>)}</Dropdown><div className="breadcrumb">{t('Workspace')}<ChevronRight size={14}/><span>{t(page)}</span></div><div className="flex items-center gap-3"><button className="btn btn-ghost btn-sm" onClick={()=>window.dispatchEvent(new Event("encodeck-palette"))}><Search size={15}/><kbd className="kbd kbd-xs">Ctrl ⇧ P</kbd></button></div></header>
 <main><div className="page-heading"><div><div className="eyebrow">{t('YOUR MEDIA. YOUR SETTINGS.')}</div><h1>{t({Builder:'Encoding workspace',Presets:'Preset library',Queue:'Encoding queue',Appearance:'Settings',Versions:'Settings',History:'History',Updates:'Settings',Languages:'Settings'}[page]!)}</h1><p>{t({Builder:'Build, fine-tune and run your next encode.',Presets:'A starting point for every workflow. Make it yours.',Queue:'Every encode, from the first frame to the final file.',Appearance:'Personalize Encodeck and manage your encoding tools.',Versions:'Install once. Choose the right engine for each project.',History:'Previous encodes, settings and execution logs.',Updates:'Check the latest Encodeck release on GitHub.',Languages:'Choose your language and extend the translation catalog.'}[page]!)}</p></div>{page==='Builder'?<button className="btn btn-outline" onClick={()=>saveDialog()}><Plus size={16}/>{t('Save preset')}</button>:page==='Presets'?<div className="flex gap-2"><button className="btn btn-outline" onClick={()=>importRef.current?.click()}><ArrowDownToLine size={16}/>{t('Import')}</button><button className="btn btn-primary" onClick={()=>saveDialog()}><Plus size={16}/>{t('New preset')}</button></div>:null}</div>
 {['Appearance','Versions','Updates','Languages'].includes(page)&&<div className="settings-navigation" role="tablist">{[{id:'Appearance',label:'Appearance',icon:Sun},{id:'Versions',label:'FFmpeg versions',icon:HardDrive},{id:'Updates',label:'Application updates',icon:Download},{id:'Languages',label:'Languages',icon:Globe2}].map(({id,label,icon:Icon})=><button role="tab" aria-selected={page===id} key={id} className={page===id?'selected':''} onClick={()=>setPage(id)}><Icon size={16}/>{t(label)}</button>)}</div>}
 {!desktop&&<div className="preview-notice"><Globe2 size={16}/>{t('Browser preview — run the desktop app to access files, install FFmpeg and encode.')}</div>}
 {(error||message)&&<div role={error?'alert':'status'} className={`alert ${error?'alert-error':'notice'} mb-5`}><span>{error||message}</span><button aria-label={t('Close')} className="btn btn-ghost btn-xs" onClick={()=>{setError('');setMessage('')}}><X size={15}/></button></div>}
 {page==='Builder'&&<div className="builder-layout"><div className="editor-column"><section className={`panel source-panel ${dragging?"drop-active":""}`}><div className="panel-heading"><h2><span className="step">01</span>{t('Source & destination')}</h2><span className="badge badge-ghost badge-sm">{t('Files or streams')}</span></div><div className="io-block"><div className="file-symbol"><Film size={24}/></div><div className="flex-1 min-w-0"><label htmlFor="source" className="field-label">{t('Source file')}</label><div className="flex gap-2"><input id="source" className="input w-full font-mono" value={form.io.input} onChange={e=>update('io',{input:e.target.value})}/><button className="btn btn-square" aria-label={t('Browse source')} onClick={()=>browse('input')} disabled={!!busy}><FolderOpen size={18}/></button></div></div></div><div className="io-output"><label htmlFor="output" className="field-label">{t('Output file')}</label><div className="flex gap-2"><input id="output" className="input w-full font-mono" value={form.io.output} onChange={e=>update('io',{output:e.target.value})}/><button className="btn btn-square" aria-label={t('Browse destination')} onClick={()=>browse('output')} disabled={!!busy}><FolderOpen size={18}/></button></div></div><div className="drop-hint">{t("Drop media and subtitle files here")}<button className="btn btn-ghost btn-xs ms-2" onClick={addFiles} disabled={!!busy}><Plus size={13}/>{t("Add files")}</button></div>{(subtitles.length>0||batch.length>0)&&<div className="attachments">{subtitles.map(path=><div className="attachment" key={path}><FileJson size={14}/><span>{filename(path)}</span><small>{t("Subtitle")}</small><button className="btn btn-ghost btn-xs" aria-label={t("Remove subtitle")} onClick={()=>setSubtitles(p=>p.filter(x=>x!==path))}><X size={13}/></button></div>)}{batch.map(path=><div className="attachment" key={path}><Film size={14}/><span>{filename(path)}</span><small>{t("Batch")}</small><button className="btn btn-ghost btn-xs" aria-label={t("Remove file")} onClick={()=>setBatch(p=>p.filter(x=>x!==path))}><X size={13}/></button></div>)}{batch.length>0&&<button className="btn btn-outline btn-sm" disabled={!!busy||!active} onClick={enqueueBatch}>{t("Encode additional files")} · {batch.length}</button>}</div>}<div className="source-footer"><span>{media?`${media.streams?.filter((s:any)=>s.codec_type==='video').map((s:any)=>`${s.width} × ${s.height}`).join(' ')} · ${Number(media.format?.duration||0).toFixed(1)} s`:t('Analyze your source to get tailored settings.')}</span><button className="btn btn-ghost btn-sm" disabled={!!busy||!desktop||!active} onClick={analyze}>{busy==='probe'?<span className="loading loading-spinner loading-xs"/>:<Search size={14}/>} {t('Analyze')}</button></div></section>
 <section className="panel"><div className="panel-heading"><h2><span className="step">02</span>{t('Encoding settings')}</h2><button className="btn btn-ghost btn-xs" onClick={()=>{editor.reset();setSelected('');setCustom(false)}}><RotateCcw size={13}/>{t('Reset')}</button></div><div className="preset-strip"><Layers3 size={17}/><label htmlFor="quick-preset" className="sr-only">{t('Preset')}</label><Dropdown id="quick-preset" className="select flex-1" value={selected} onChange={e=>applyPreset(e.target.value)}><option value="">{t('Custom settings')}</option>{groups.map(g=><optgroup key={g.id} label={t(g.name)}>{g.data.map(p=><option key={p.value} value={p.value}>{p.name}</option>)}</optgroup>)}{saved.length>0&&<optgroup label={t('My presets')}>{saved.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</optgroup>}</Dropdown><button className="btn btn-ghost btn-sm" disabled={!media} onClick={autoPreset}><Sparkles size={15}/>{t('Auto')}</button></div><div className="tabs tabs-border editor-tabs" role="tablist">{['Format','Video','Audio','Filters','Options'].map(key=><button key={key} role="tab" aria-selected={tab===key} aria-controls="settings-panel" className={`tab ${tab===key?'tab-active':''}`} onClick={()=>setTab(key)}>{t(key)}</button>)}</div><div id="settings-panel" role="tabpanel" aria-label={t(tab)} className="settings-body">{tab==='Format'&&<FormatSection value={form.format} onChange={updateFormat}/>} {tab==='Video'&&<VideoSection value={form.video} container={form.format.container||'mp4'} onChange={updateVideo}/>} {tab==='Audio'&&<AudioSection value={form.audio} container={form.format.container||'mp4'} onChange={p=>update('audio',p)}/>} {tab==='Filters'&&<FiltersSection value={form.filters} onChange={p=>update('filters',p)}/>} {tab==='Options'&&<OptionsSection value={form.options} onChange={p=>update('options',p)}/>}</div></section></div>
 <aside className="output-column"><section className="panel command-panel"><div className="panel-heading"><h2><Terminal size={17}/>{t('Command preview')}</h2><span className="badge badge-sm badge-outline">PowerShell</span></div><div className="command-meta"><span className="status status-success status-xs"/>{t('Updates as you edit')}</div><pre dir="ltr" className="command-code"><code>{json?JSON.stringify(combined.plans,null,2):command||combined.error}</code></pre><div className="command-actions"><label className="flex gap-2 items-center text-xs"><input type="checkbox" className="checkbox checkbox-xs" checked={json} onChange={e=>setJson(e.target.checked)}/>JSON argv</label><button className="btn btn-ghost btn-sm" onClick={()=>action('copy',async()=>{await navigator.clipboard.writeText(json?JSON.stringify(combined.plans,null,2):command);setMessage(t('Copied'))})}><Copy size={14}/>{t('Copy')}</button></div><div className="encode-summary"><div><span>{t('Container')}</span><strong>{form.format.container?.toUpperCase()}</strong></div><div><span>{t('Video codec')}</span><strong>{form.video.codec}</strong></div><div><span>{t('Audio codec')}</span><strong>{form.audio.codec}</strong></div><div><span>{t('Resolution')}</span><strong>{form.video.size==='source'?t('Source'):form.video.size==='custom'?`${form.video.width} × ${form.video.height}`:`${form.video.size}px`}</strong></div></div><div className="run-area"><button className="btn btn-primary w-full" disabled={!!busy||!combined.plans.length||!desktop||!active} onClick={enqueue}><Play size={17} fill="currentColor"/>{t(running.length?'Add to queue':'Run command')}<span className="ms-auto text-xs opacity-60">{derived.plans.length===2?'2 PASS':''}</span></button><p>{active?`${t('Using')} FFmpeg ${active.name}`:t('Configure FFmpeg in Versions to start.')}</p></div></section><div className="tip-block"><Sparkles size={19}/><div><h3>{t('A smarter starting point')}</h3><p>{t('Analyze a source, then use Auto to choose compatible settings without upscaling.')}</p><button className="text-link" onClick={()=>setPage('Presets')}>{t('Explore presets')}<ArrowUpRight size={13}/></button></div></div><details className="advanced"><summary>{t('Advanced command editor')}</summary><p>{t('Edit JSON argument arrays. Each array runs as one FFmpeg process; no shell is used.')}</p><label className="flex items-center gap-2"><input type="checkbox" className="checkbox checkbox-sm" checked={custom} onChange={e=>{if(e.target.checked)setCustomArgs(JSON.stringify(combined.plans,null,2));setCustom(e.target.checked)}}/>{t('Use custom arguments')}</label>{custom&&<textarea dir="ltr" aria-label="Custom JSON arguments" className="textarea font-mono w-full mt-3" rows={12} value={customArgs} onChange={e=>setCustomArgs(e.target.value)}/>}</details></aside>
 <section className="panel activity-panel"><div className="panel-heading"><h2><ListVideo size={17}/>{t('Activity')}</h2><button className="text-link" onClick={()=>setPage('Queue')}>{t('View queue')}<ArrowUpRight size={14}/></button></div>{current?<div className="activity-job"><div className="flex items-center justify-between gap-3"><strong className="truncate">{filename(current.output)}</strong><span className="badge badge-outline">{t(current.status)}</span></div><progress className="progress progress-primary" value={current.progress} max={100}/><pre dir="ltr">{current.logs.slice(-3).join('\n')||t('Waiting for the engine')}</pre></div>:<div className="empty-activity"><span className="terminal-glyph">&gt;_</span><div><strong>{t('Ready when you are')}</strong><p>{t('Your encoding progress and logs will appear here.')}</p></div><span className="badge badge-ghost">{t('No active jobs')}</span></div>}</section></div>}
 {page==='Presets'&&<><div className="library-toolbar"><label className="input flex-1"><Search size={16}/><input aria-label={t('Search presets')} placeholder={t('Search presets')} value={search} onChange={e=>setSearch(e.target.value)}/></label><Dropdown className="select" aria-label={t('Category')} value={category} onChange={e=>setCategory(e.target.value)}>{['All','My presets',...groups.map(g=>g.name)].map(g=><option key={g} value={g}>{t(g)}</option>)}</Dropdown><button className="btn btn-outline" disabled={!saved.length} onClick={()=>downloadJson('commander-presets.json',{version:1,presets:saved})}><Download size={16}/>{t('Export')}</button></div><div className="preset-grid">{[...saved.map(p=>({value:p.id,name:p.name,group:'My presets'})),...recipes].filter(p=>(category==='All'||p.group===category)&&p.name.toLowerCase().includes(search.toLowerCase())).map(p=><article className="card preset-card" key={p.value}><div className="preset-card-top"><span className="preset-icon">{p.group==='Audio Only'?<AudioLines size={21}/>:<Film size={21}/>}</span><span className="badge badge-ghost badge-sm">{t(p.group)}</span></div><h2>{p.name}</h2><p>{t(p.group==='My presets'?'Your saved encoding settings.':'Ready-to-use settings. Adjust after applying.')}</p><div className="preset-card-actions"><button className="btn btn-outline btn-sm" onClick={()=>applyPreset(p.value)}>{t('Use preset')}<ChevronRight size={14}/></button>{p.group==='My presets'&&<div className="flex gap-1"><button className="btn btn-ghost btn-sm btn-square" aria-label={t('Update preset')} onClick={()=>saveDialog(p.value)}><Settings2 size={15}/></button><button className="btn btn-ghost btn-sm btn-square" aria-label={t('Delete preset')} onClick={()=>action('delete',async()=>{await persist(saved.filter(s=>s.id!==p.value));setMessage(t('Preset removed'))})}><Trash2 size={15}/></button></div>}</div></article>)}</div></>}
 {(page==='Queue'||page==='History')&&<div className="queue-layout"><section className="panel"><div className="panel-heading"><h2>{t('Jobs')} <span className="badge badge-ghost">{jobs.length}</span></h2><span className="text-xs text-muted">{t('One encode at a time')}</span></div>{jobs.length?jobs.toReversed().filter(j=>page!=="History"||!["queued","running"].includes(j.status)).map(j=><div key={j.id} className={`queue-row ${current?.id===j.id?'selected':''}`}><button className="queue-select" onClick={()=>setJobId(j.id)}><Film size={21}/><span><strong>{filename(j.output)}</strong><small>{new Date(j.created*1000).toLocaleString(locale)} · {t('Pass')} {j.pass}/{j.plans.length}</small></span></button><span className="badge badge-outline">{t(j.status)}</span><progress className="progress progress-primary" value={j.progress} max={100}/>{['running','queued'].includes(j.status)?<button className="btn btn-ghost btn-sm" onClick={()=>action('cancel',async()=>{await native('cancel_job',{id:j.id});await refresh()})}>{t('Cancel')}</button>:<button className="btn btn-ghost btn-sm" disabled={!!busy} onClick={()=>action('retry',async()=>{const id=await native<string>('enqueue',{plans:j.plans,output:j.output,duration:j.duration});setJobId(id);await refresh()})}>{t('Retry')}</button>}</div>):<div className="empty-state"><ListVideo size={36}/><h2>{t('No jobs yet')}</h2><p>{t('Start an encode from the workspace.')}</p><button className="btn btn-primary" onClick={()=>setPage('Builder')}>{t('Open workspace')}</button></div>}</section>{current&&<section className="panel"><div className="panel-heading"><h2>{t('Execution log')}</h2><button className="btn btn-ghost btn-sm" disabled={current.status!=='completed'} onClick={()=>action('reveal',()=>native('reveal_output',{path:current.output}))}><FolderOpen size={16}/>{t('Show file')}</button></div><div className="log-meta"><p className="break-all">{current.output}</p><small className="break-all">{current.binary}</small></div><pre dir="ltr" className="full-log">{current.logs.join('\n')||t('Waiting for the engine')}</pre></section>}</div>}
 {page==='Versions'&&<div className="versions-layout"><section className="panel"><div className="panel-heading"><h2><HardDrive size={18}/>{t('Installed versions')}</h2><button className="btn btn-outline btn-sm" disabled={!!busy} onClick={()=>action('import-version',async()=>{const path=await open({title:t('Select FFmpeg executable'),multiple:false});if(typeof path==='string'){await native('import_version',{path});await refresh()}})}><FolderOpen size={15}/>{t('Import local')}</button></div>{snap.config.versions.length?snap.config.versions.map(v=><div className="version-row" key={v.id}><span className="version-icon"><Terminal size={22}/></span><div className="flex-1 min-w-0"><h3>FFmpeg {v.name} {active?.id===v.id&&<span className="badge badge-primary badge-sm">{t('Active')}</span>}</h3><p className="break-all">{v.path}</p><small>{v.managed?'Gyan · SHA-256 '+t('Verified'):t('Local binary')}</small></div>{active?.id!==v.id&&<button className="btn btn-outline btn-sm" disabled={!!busy} onClick={()=>action('select',async()=>{await native('select_version',{id:v.id});await refresh()})}>{t('Activate')}</button>}<button className="btn btn-ghost btn-square btn-sm" disabled={active?.id===v.id||!!busy} aria-label={t('Remove version')} onClick={()=>action('remove',async()=>{await native('remove_version',{id:v.id});await refresh()})}><Trash2 size={15}/></button></div>):<div className="empty-state"><Download size={34}/><h2>{t('Install your encoding engine')}</h2><p>{t('Choose a release below or import ffmpeg and ffprobe from your computer.')}</p></div>}</section><section className="panel"><div className="panel-heading"><h2>{t('Available releases')}</h2><button className="btn btn-outline btn-sm" disabled={!!busy||!desktop} onClick={()=>action('catalog',async()=>setReleases(await native<Release[]>('catalog')))}><RotateCcw size={14}/>{t('Check releases')}</button></div><div className="release-note"><ShieldCheck size={20}/><p>{t('Windows x64 builds from Gyan. Downloads are verified with SHA-256 and stored separately for each version.')}</p></div>{snap.installing&&<div className="alert notice m-4"><span className="loading loading-spinner loading-sm"/>{snap.installing}</div>}{releases.map((r,i)=><div className="release-row" key={r.tag}><div><h3>FFmpeg {r.tag} {i===0&&<span className="badge badge-outline badge-sm">{t('Latest')}</span>}</h3><p>{t('Essentials build')} · {(r.size/1_000_000).toFixed(0)} MB</p></div><button className="btn btn-primary btn-sm" disabled={!!busy||snap.config.versions.some(v=>v.id===r.tag)} onClick={()=>action('install',async()=>{await native('install_version',{tag:r.tag});await refresh();setMessage(t('FFmpeg installed'))})}><Download size={15}/>{t(snap.config.versions.some(v=>v.id===r.tag)?'Installed':'Install')}</button></div>)}</section></div>}
 {page==='Appearance'&&<section className="panel"><div className="panel-heading"><h2><Sun size={18}/>{t('Appearance')}</h2></div><div className="p-6"><p className="text-muted mb-5">{t('Choose a comfortable appearance for your workspace.')}</p><div className="theme-options settings-themes"><button className={!light?'selected':''} onClick={()=>setLight(false)}><span className="theme-swatch dark-swatch"><i/><i/><i/></span><Moon size={17}/>{t('Dark theme')}{!light&&<Check size={15}/>}</button><button className={light?'selected':''} onClick={()=>setLight(true)}><span className="theme-swatch light-swatch"><i/><i/><i/></span><Sun size={17}/>{t('Light theme')}{light&&<Check size={15}/>}</button></div><button className="btn btn-outline mt-6" onClick={()=>setOnboarding(true)}>{t('Restart onboarding')}</button></div></section>}
 {page==='Updates'&&<section className="panel"><div className="panel-heading"><h2>Encodeck · 1.0.0</h2><button className="btn btn-primary" disabled={!!busy||!desktop} onClick={()=>action('update-check',async()=>setAppRelease(await native('check_app_update')))}><RotateCcw size={15}/>{t('Check for updates')}</button></div><div className="p-6 space-y-4"><p>{t('Updates are checked against the project GitHub releases. No media is uploaded.')}</p>{appRelease&&<><h3 className="text-lg">{appRelease.available?t('Update available'):t('You are up to date')} · {appRelease.version}</h3><p className="whitespace-pre-wrap text-muted text-sm">{appRelease.notes}</p><button className="btn btn-outline" onClick={()=>action('release',()=>native('open_release'))}><ArrowUpRight size={16}/>{t('Open downloads')}</button></>}</div></section>}{page==='Languages'&&<section className="panel language-panel"><div className="panel-heading"><h2><Globe2 size={19}/>{t('Interface language')}</h2><span className="badge badge-ghost">BCP 47 · Unicode · RTL</span></div><div className="p-6 space-y-5"><Dropdown className="select w-full max-w-md" value={locale} aria-label={t('Interface language')} onChange={e=>selectLocale(e.target.value)}>{languages.map(l=><option key={l.code} value={l.code}>{l.name}</option>)}</Dropdown><div className="translation-meter"><span>{t('Translated interface')} <strong>{coverage(locale)}%</strong></span><progress className="progress progress-primary" value={coverage(locale)} max={100}/><p>{t('Translations are generated and bundled by Encodeck. Technical FFmpeg logs, commands and file paths retain their original content.')}</p><p>{t('Machine translations may contain wording errors. You can switch languages at any time.')}</p></div></div></section>}
 </main><footer className="app-footer"><span><span className="status status-success status-xs"/>{t('Built for local workflows')}</span><span>{selectedRecipe||t('Custom settings')}<span className="footer-dot">·</span>Encodeck</span></footer></div>
 <Onboarding visible={onboarding} onDone={()=>{setOnboarding(false);localStorage.setItem('encodeck-onboarded','true')}} locale={locale} onLocale={selectLocale} light={light} onTheme={setLight} snapshot={snap} onRefresh={refresh}/>
 <CommandPalette actions={[...['Builder','Presets','Queue','History','Versions','Updates','Languages'].map(id=>({id,label:id,run:()=>setPage(id)})),{id:'add-files',label:'Add media or subtitles',run:()=>void addFiles()},{id:'save-preset',label:'Save preset',run:()=>saveDialog()},{id:'import-presets',label:'Import presets',run:()=>importRef.current?.click()},{id:'export-presets',label:'Export presets',run:()=>downloadJson('encodeck-presets.json',{version:1,presets:saved})},{id:'analyze',label:'Analyze source',run:()=>void analyze()},{id:'run',label:'Run command',run:()=>void enqueue()},{id:'theme',label:light?'Dark theme':'Light theme',run:()=>setLight(!light)}]}/>
 <dialog ref={modal} className="modal"><div className="modal-box"><form onSubmit={e=>{e.preventDefault();void savePreset()}}><h2 className="text-xl font-semibold mb-2">{t(editId?'Update preset':'Save preset')}</h2><p className="text-sm text-muted mb-5">{t('Save the current settings without source or destination paths.')}</p><label htmlFor="preset-name" className="field-label">{t('Preset name')}</label><input id="preset-name" className="input w-full" autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><div className="modal-action"><button type="button" className="btn btn-ghost" onClick={()=>modal.current?.close()}>{t('Cancel')}</button><button className="btn btn-primary" type="submit" disabled={!!busy}><Check size={16}/>{t('Save')}</button></div></form></div><form method="dialog" className="modal-backdrop"><button>{t('Close')}</button></form></dialog>
 <input ref={importRef} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void action('import',async()=>{if(f.size>2_000_000)throw new Error('File too large');const data=JSON.parse(await f.text());if(!Array.isArray(data.presets)||data.presets.some((p:any)=>typeof p.name!=='string'||!p.data||typeof p.data!=='object'))throw new Error('Invalid preset file');await persist([...saved,...data.presets.map((p:any)=>({id:crypto.randomUUID(),name:p.name,data:p.data}))]);setMessage(t('Presets imported'))});e.target.value=''}}/>
 <input ref={langRef} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void action('language',async()=>{if(f.size>2_000_000)throw new Error('File too large');const code=importLanguagePack(JSON.parse(await f.text()));selectLocale(code);setMessage(t('Language pack imported'))});e.target.value=''}}/>
 </div>;
}




