import {useEffect,useRef,useState} from 'react';
import {Search,ArrowUpRight} from 'lucide-react';
import {t} from './i18n';
export interface PaletteAction {id:string;label:string;run:()=>void;shortcut?:string}
export default function CommandPalette({actions}:{actions:PaletteAction[]}){
 const dialog=useRef<HTMLDialogElement>(null);const input=useRef<HTMLInputElement>(null);const [query,setQuery]=useState(''),[index,setIndex]=useState(0);
 const filtered=actions.filter(a=>t(a.label).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const open=()=>{setQuery('');setIndex(0);dialog.current?.showModal();input.current?.focus()};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();open()}};const trigger=()=>open();window.addEventListener('keydown',key);window.addEventListener('encodeck-palette',trigger);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('encodeck-palette',trigger)}},[]);
 const execute=(a?:PaletteAction)=>{if(a){dialog.current?.close();a.run()}};
 return <dialog ref={dialog} className="modal command-palette"><div className="modal-box palette-box"><div className="palette-search"><Search size={21}/><input ref={input} role="combobox" aria-label={t('Search pages or actions')} aria-expanded={true} aria-controls="palette-list" aria-activedescendant={filtered[index]?`action-${filtered[index].id}`:undefined} placeholder={t('Search pages or actions')} value={query} onChange={e=>{setQuery(e.target.value);setIndex(0)}} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setIndex(i=>{const next=(i+(e.key==='ArrowDown'?1:-1)+Math.max(filtered.length,1))%Math.max(filtered.length,1);document.getElementById(`action-${filtered[next]?.id}`)?.scrollIntoView({block:'nearest'});return next})}if(e.key==='Enter'){e.preventDefault();execute(filtered[index])}}}/><kbd className="kbd kbd-sm">Esc</kbd></div><div id="palette-list" role="listbox" aria-label={t('Actions')} className="palette-results">{filtered.map((a,i)=><button role="option" aria-selected={index===i} id={`action-${a.id}`} className={index===i?'selected':''} key={a.id} onPointerMove={()=>setIndex(i)} onClick={()=>execute(a)}><ArrowUpRight size={18}/><span>{t(a.label)}</span>{a.shortcut&&<kbd>{a.shortcut}</kbd>}</button>)}{!filtered.length&&<p className="p-6 text-muted">{t('No matching actions')}</p>}</div><div className="palette-footer">↑ ↓ · Enter <span>{t('Navigate and select')}</span></div></div><form method="dialog" className="modal-backdrop"><button>{t('Close')}</button></form></dialog>
}
