import logoSvg from './logo.svg?raw';
import Dropdown from './components/ui/Dropdown';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Check,Download,FolderOpen,Keyboard,Film,Sun,Moon,ShieldCheck,Terminal} from 'lucide-react';
import {open} from '@tauri-apps/plugin-dialog';
import {native,desktop,type Snapshot,type Release} from './native';
import {t,languages} from './i18n';
export default function Onboarding({visible,onDone,locale,onLocale,light,onTheme,snapshot,onRefresh}:{visible:boolean;onDone:()=>void;locale:string;onLocale:(v:string)=>void;light:boolean;onTheme:(v:boolean)=>void;snapshot:Snapshot;onRefresh:()=>Promise<void>}){
 const modal=useRef<HTMLDialogElement>(null);const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(visible){setStep(0);modal.current?.showModal()}else modal.current?.close()},[visible]);
 const titles=['Welcome to Encodeck','Make yourself at home','Choose your appearance','Set up your encoding engine','Your workflow, simplified','Ready for your first encode'];
 async function install(){setBusy(true);setError('');try{const releases=await native<Release[]>('catalog');if(!releases.length)throw Error('No FFmpeg release available');await native('install_version',{tag:releases[0].tag});await onRefresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function local(){setBusy(true);setError('');try{const path=await open({multiple:false,title:t('Select FFmpeg executable')});if(typeof path==='string'){await native('import_version',{path});await onRefresh()}}catch(e){setError(String(e))}finally{setBusy(false)}}
 function next(){setError('');if(step===5)onDone();else setStep(s=>s+1)}
 return <dialog className="modal onboarding-modal" ref={modal} onCancel={e=>{e.preventDefault();if(!busy)onDone()}}><div className="modal-box onboarding-box"><div className="onboarding-top"><span>ENCODECK <span className="text-muted">/ {t('Getting started')}</span></span><button className="btn btn-ghost btn-sm" disabled={busy} onClick={onDone}>{t('Skip for now')}</button></div><div className="onboarding-content"><div className={step===0?"onboarding-logo":"onboarding-icon"}>{step===0?<span role="img" aria-label="Encodeck" dangerouslySetInnerHTML={{__html:logoSvg}}/>:step===1?<span>文 A</span>:step===2?<Sun size={34}/>:step===3?<Terminal size={34}/>:step===4?<Keyboard size={34}/>:<Check size={36}/>}</div><p className="eyebrow">{t('Step')} {step+1} / 6</p><h1>{t(titles[step])}</h1>
 {step===0&&<><p>{t('A clear workspace for powerful media conversions. Build commands visually, save your settings and let FFmpeg do the work.')}</p><div className="onboarding-features"><span><ShieldCheck size={17}/>{t('Your files stay on your computer')}</span><span><Film size={17}/>{t('Video, audio and subtitles')}</span><span><Keyboard size={17}/>{t('Built for keyboard and mouse')}</span></div></>}
 {step===1&&<><p>{t('Choose the language used throughout the application. You can change it later in Settings.')}</p><label htmlFor="onboarding-language" className="field-label mt-6">{t('Interface language')}</label><Dropdown id="onboarding-language" className="select w-full" value={locale} onChange={e=>onLocale(e.target.value)}>{languages.map(l=><option key={l.code} value={l.code}>{l.name}</option>)}</Dropdown><p className="onboarding-note">{t('Translations are included offline. Right-to-left languages are supported.')}</p></>}
 {step===2&&<><p>{t('Choose a comfortable appearance for your workspace.')}</p><div className="theme-options"><button className={!light?'selected':''} onClick={()=>onTheme(false)}><span className="theme-swatch dark-swatch"><i/><i/><i/></span><Moon size={17}/>{t('Dark theme')}{!light&&<Check size={15}/>}</button><button className={light?'selected':''} onClick={()=>onTheme(true)}><span className="theme-swatch light-swatch"><i/><i/><i/></span><Sun size={17}/>{t('Light theme')}{light&&<Check size={15}/>}</button></div></>}
 {step===3&&<><p>{t('Encodeck needs FFmpeg and ffprobe to process and analyze media. Install a compatible version or select an existing binary.')}</p>{snapshot.config.versions.length?<div className="alert notice mt-6"><Check size={18}/>{t('Encoding engine ready')} · {snapshot.config.versions.find(v=>v.id===snapshot.config.active)?.name}</div>:<div className="flex flex-col gap-3 mt-6"><button className="btn btn-primary" disabled={busy||!desktop} onClick={install}>{busy?<span className="loading loading-spinner loading-sm"/>:<Download size={17}/>} {t('Install FFmpeg automatically')}</button><button className="btn btn-outline" disabled={busy||!desktop} onClick={local}><FolderOpen size={17}/>{t('Use an existing installation')}</button></div>}{snapshot.installing&&<p className="onboarding-note" role="status">{snapshot.installing}</p>}{!desktop&&<p className="onboarding-note">{t('Installation is available in the desktop application.')}</p>}</>}
 {step===4&&<><p>{t('Drop your media into the workspace, choose a preset, then run your command. Progress and logs are saved in History.')}</p><div className="shortcut-list"><div><span>{t('Open command palette')}</span><kbd className="kbd">Ctrl ⇧ P</kbd></div><div><span>{t('Navigate actions')}</span><kbd className="kbd">↑ ↓ Enter</kbd></div><div><span>{t('Close a dialog')}</span><kbd className="kbd">Esc</kbd></div></div></>}
 {step===5&&<><p>{t('Your workspace is ready. Every command is visible before execution, and existing files are protected by default.')}</p><div className="onboarding-features"><span><Check size={17}/>{t('Preferences saved')}</span><span><Check size={17}/>{t('Presets ready to use')}</span><span><ShieldCheck size={17}/>{t('No media upload required')}</span></div>{!snapshot.config.versions.length&&<p className="onboarding-note">{t('You can install FFmpeg later in Settings before running your first command.')}</p>}</>}
 {error&&<div className="alert alert-error mt-4" role="alert">{error}</div>}</div><div className="onboarding-navigation"><button className="btn btn-ghost" disabled={step===0||busy} onClick={()=>{setError('');setStep(s=>s-1)}}><ArrowLeft size={16}/>{t('Previous')}</button><div className="onboarding-dots" aria-label={t('Onboarding progress')}>{titles.map((title,i)=><button key={title} className={i===step?'active':i<step?'done':''} aria-label={`${t('Step')} ${i+1}: ${t(title)}`} aria-current={step===i?'step':undefined} disabled={busy} onClick={()=>{setError('');setStep(i)}}/>)}</div><button className="btn btn-primary" disabled={busy} onClick={next}>{t(step===5?'Start encoding':'Next')}<ArrowRight size={16}/></button></div></div></dialog>
}


