import {Children,isValidElement,useId,useRef,useState,type ReactNode} from 'react';
import {ChevronDown,Check} from 'lucide-react';
interface Choice{value:string;label:ReactNode;group?:ReactNode;disabled?:boolean}
interface Props {id?:string;value?:string;children:ReactNode;className?:string;onChange?:(e:{target:{value:string}})=>void;disabled?:boolean;'aria-label'?:string}
function flatten(children:ReactNode,group?:ReactNode):Choice[]{return Children.toArray(children).flatMap(c=>{if(!isValidElement<any>(c))return[];const props=c.props as {children:ReactNode;label:ReactNode;value?:string;disabled?:boolean};if(c.type==='optgroup')return flatten(props.children,props.label);if(c.type==='option')return[{value:String(props.value??props.children),label:props.children,group,disabled:props.disabled}];return[]})}
export default function Dropdown({id,value,children,className='',onChange,disabled,...aria}:Props){
 const generated=useId(),listId=`list-${id||generated}`;const button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);const [opened,setOpened]=useState(false),[index,setIndex]=useState(0),[box,setBox]=useState({left:0,top:0,width:200,maxHeight:250});const typeahead=useRef(''),lastType=useRef(0);const options=flatten(children);const selected=options.find(o=>o.value===String(value))||options[0];
 function show(){if(disabled)return;let r=button.current!.getBoundingClientRect();if(window.innerHeight-r.bottom<160){button.current!.scrollIntoView({block:'center',inline:'nearest'});r=button.current!.getBoundingClientRect()}setBox({left:Math.max(8,Math.min(r.left,window.innerWidth-r.width-8)),top:r.bottom+5,width:r.width,maxHeight:Math.max(40,Math.min(300,window.innerHeight-r.bottom-18))});setIndex(Math.max(0,options.findIndex(o=>o.value===String(value))));menu.current?.showPopover();setOpened(true)}
 function close(){menu.current?.hidePopover();setOpened(false)}
 function choose(i:number){const option=options[i];if(!option||option.disabled)return;onChange?.({target:{value:option.value}});close();button.current?.focus()}
 return <span className="dropdown-field"><button ref={button} id={id} type="button" role="combobox" aria-haspopup="listbox" aria-controls={listId} aria-expanded={opened} aria-activedescendant={opened?`${listId}-${index}`:undefined} aria-label={aria['aria-label']} disabled={disabled} className={`${className} custom-select`} onClick={()=>opened?close():show()} onKeyDown={e=>{if(e.key==='Escape'){close();return}if(e.key==='Tab'){close();return}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(!opened){show();return}let next=e.key==='Home'?0:e.key==='End'?options.length-1:(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;setIndex(next);document.getElementById(`${listId}-${next}`)?.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'||e.key===' '){e.preventDefault();if(opened)choose(index);else show()}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey){const now=Date.now();typeahead.current=(now-lastType.current>800?'':typeahead.current)+e.key.toLocaleLowerCase();lastType.current=now;const found=options.findIndex(o=>String(o.label).toLocaleLowerCase().startsWith(typeahead.current));if(found>=0){if(!opened)show();setIndex(found);document.getElementById(`${listId}-${found}`)?.scrollIntoView({block:'nearest'})}}}}><span>{selected?.label}</span><ChevronDown size={14}/></button><div ref={menu} id={listId} popover="auto" role="listbox" aria-label={aria['aria-label']} className="select-menu" style={box} onToggle={e=>setOpened((e.nativeEvent as ToggleEvent).newState==='open')}>{options.map((o,i)=><div key={`${o.value}-${i}`}>{o.group&&o.group!==options[i-1]?.group&&<div className="select-group">{o.group}</div>}<button type="button" tabIndex={-1} id={`${listId}-${i}`} role="option" aria-selected={o.value===String(value)} disabled={o.disabled} className={i===index?'highlighted':''} onPointerMove={()=>setIndex(i)} onClick={()=>choose(i)}><span>{o.label}</span>{o.value===String(value)&&<Check size={14}/>}</button></div>)}</div></span>
}

